CONFIG += no_fixpath
QT = core gui testlib widgets
CONFIG += no_fixpath
QT = core gui testlib widgets
CONFIG += no_fixpath
QT = core gui testlib widgets
CONFIG += no_fixpath
QT = core gui testlib widgets
CONFIG += no_fixpath
QT = core gui testlib widgets
CONFIG += no_fixpath
QT = core gui testlib widgets
